### ISSUE TITLE
The meaning of methods-summaries.txt

### ISSUE THREAD

**Issue by sumy7** [h3xstream/find-sec-bugs#103]
I want to add some rules to the [methods-summaries.txt](https://github.com/h3xstream/find-sec-bugs/blob/master/plugin/src/main/resources/taint-config/methods-summaries.txt) file, but I do not understand the meaning of the number before or after `#`.
I need some help.

---
Example

    java/lang/StringBuilder.append(Ljava/lang/String;)Ljava/lang/StringBuilder;:0,1#1
    java/util/StringTokenizer.<init>(Ljava/lang/String;)V:0#1,2

---

**Comment by formanek** [comment]
These numbers specify method parameters starting from the right from 0 (note that long and double types takes two slots). For a non-static *n*-parameter method (without long and doubles), number *n* means the object instance. The objects specified by numbers before `#` are used to extract their taint value and then merged into resulting taint, which is set, when the method return value is used. The numbers after `#` are used to specify mutable objects, which accept the resulting taint too. Constructors are specific, because we usually need to transfer the taint one level deeper in the operand stack, so the specification after `#` is *n,n+1*.

Do you want to add rules from Java API, some dependency or own methods? I could probably add them for you or at least give you a concrete advice or check the result.

**Comment by sumy7** [comment]
@formanek , thanks.
I have a piece of code, please help me see if I understand correctly.

    jdbcRs = new JdbcRowSetImpl(con);
jdbcRs.setCommand("select * from COFFEES");
jdbcRs.execute();

**Comment by sumy7** [comment]
@formanek , thanks.
I have a piece of code, please help me see if I understand correctly.

    jdbcRs = new JdbcRowSetImpl(con);
    jdbcRs.setCommand("select * from COFFEES");
    jdbcRs.execute(); 

For the LINE 2:

    com/sun/rowset/JdbcRowSetImpl.setCommand(Ljava/lang/String;)V:0,1#1

The [docs](http://docs.oracle.com/cd/E17824_01/dsc_docs/docs/jscreator/apis/rowset/com/sun/rowset/JdbcRowSetImpl.html) for the Class `JdbcRowSetImpl`.

**Comment by h3xstream** [comment]
Quick note : There seems to be a [lot of implementations](http://docs.oracle.com/javase/1.5.0/docs/api/javax/sql/RowSet.html) of the `RowSet` interface including [WebSphere](http://docs.oracle.com/javase/1.5.0/docs/api/javax/sql/RowSet.html) and Sun specific implementations.

**Comment by formanek** [comment]
@sumy7 The summary is right, if you want to mark `JdbcRowSetImpl` instances as tainted from its argument, but this makes sense only if there is a taint sink accepting these objects or there are some configured taint transfer methods to convert it to a type accepted by some sink (usually `String`) or some supported object type, which is later converted. If you want to detect usage of `jdbcRs.setCommand` with a tainted argument, you need to define a taint sink in a taint detector. Taint analysis classes are independent on taint sinks and method summaries are used only to track the taint state of taint sinks arguments.

@h3xstream I'm currently adding support for inheritance for method summaries, so implemented configured methods are supported automatically (but constructor still have to be configured). Similar thing could be done for taint sinks too.
