### ISSUE TITLE
SQL Injection detected when StringBuilder is used with constant strings

### ISSUE THREAD

**Issue by domak** [h3xstream/find-sec-bugs#14]
Hi, 

As soon as I see a StringBuilder in JPA EntityManager.createQuery(), an SQL injection is detected:

```
StringBuilder buff = new StringBuilder("from Tiers t");
// add conditional where clauses

TypedQuery<Tiers> query1 = em.createQuery(buff.toString(), Tiers.class); // SQL injection detected
query1.getResultList();
```

Is it possible to improve detector by checking that no input parameter (method parameter or attribute) has been added to the StringBuilder? 

On the code I try to verify, there are a lot of where clauses added if a parameter is not null (and the developper uses setParameter() method)

**Comment by h3xstream** [comment]
The initial code sample with StringBuilder is now supported. Even much more advanced flow analysis are done in **1.4.2**.
The release version will be available very soon.

**Comment by ThrawnCA** [comment]
I'm still getting false positives from SQL_INJECTION_HIBERNATE when assembling a constant string:

    private static final String NTP_QUERY = new StringBuilder(
                    " select os.name, p.dateProcessed, cd.title || ' ' || cd.givenName || ' ' || cd.familyName, p.amount ")
            .append("   from Statement as st ")
            .append("  inner join st.paymentRequest as pr ")
            .append("  inner join pr.onlineService as os ")
            .append("   left outer join pr.contactDetails as cd ")
            .append("  inner join st.payment as p ")
            .append("  where p.dateProcessed >= :startDate ")
            .append("    and p.dateProcessed <= :endDate")
            .append("  order by p.id")
            .toString();

and then passing it to Hibernate Session `createQuery`.

**Comment by h3xstream** [comment]
@ThrawnCA Please open a new ticket for this case.
Field are different beast.

Unless the type is primitive `final` instance can be altered. Here it is an immutable type `String` with a twist. In general, we didn't need to worry about constant String because the compiler does optimization were it will copy the content of constant everywhere they are used (inline into the code of methods). This late initialization does not allow the compiler to optimize the use of the string.

I think it is worth to be supported.

**Comment by h3xstream** [comment]
I have created #385
