### ISSUE TITLE
RFE: detect XSS in Freemarker templates

### ISSUE THREAD

**Issue by ThrawnCA** [h3xstream/find-sec-bugs#48]
Where I work, we tend to use Freemarker for our view technology, rather than JSP, and unfortunately, while Freemarker certainly has built-in escaping capabilities, they can't be set as a global default.

How feasible is it for the checks that currently work on JSP pages to be adapted to Freemarker templates? I would be happy to do some work on this if it seems feasible.

**Comment by h3xstream** [comment]
Unfortunately, FindBugs detectors can only analyze Java classes. Since Freemarker template aren't translate to bytecode, it is not possible at the moment. If it change (new feature in FB), let me know I would be interested to write new rules.

I highly suggest you to mention the suggestion on the [FindBugs mailing-list](https://mailman.cs.umd.edu/mailman/listinfo/findbugs-discuss).

**Comment by ThrawnCA** [comment]
Ah, of course. Actually, the lack of compilation is (for us) one of the benefits of using Freemarker.

Thanks anyway.

**Comment by h3xstream** [comment]
Yeah it is a limitation on FindBugs side. XML/YAML/JSON/properties could also benefit from a "free-form" analysis.

**Comment by h3xstream** [comment]
If this next feature gets implemented, this feature request will be reopen.
https://github.com/findbugsproject/findbugs/issues/77
