### ISSUE TITLE
EntityManager createQuery trips SECSQLIJPA even with safe usage

### ISSUE THREAD

**Issue by ThrawnCA** [h3xstream/find-sec-bugs#76]
Using the ``createQuery`` and ``createNativeQuery`` methods of a JPA EntityManager trips the SECSQLIJPA detector even if there are no tainted inputs.

This class trips the detector for me:

    package findbugs.sample;

    import javax.persistence.EntityManager;
    import javax.persistence.PersistenceContext;
    import javax.persistence.Query;

    public class TestInjectionWithConstantString {

        @PersistenceContext
        private EntityManager entityManager;

        public void queryWithConstantString() {
            entityManager.createQuery("foo");
            entityManager.createNativeQuery("foo");
        }

    }

**Comment by h3xstream** [comment]
Yup. Confirmed. Note that the false positive are probably mark as LOW. (Contrary to Medium or High for Higher level confidence)
It was intended in the change done by @formanek.

I think I will be better to remove those false positives from the report.

**Comment by h3xstream** [comment]
I'm planning to an urgent release of 1.4.3 ASAP.

**Comment by formanek** [comment]
Yes, it is intended as an insurance in a case of a bad analysis, low confidence warnings are not shown in FindBugs GUI and I was inspired by h3xstream's code, when implemented this, so I have thought, it is ok. But if confidence levels are not supported by plugins, we should change it of course.

The easiest way of solving this is change of priority from low to ignore. Since I would like to have a simple way of checking, what is ignored, I think we could make a new debug rule (ignored by ordinary users) such as *Taint sink with safe sources* and report the bug instance here instead.

We should also consider, what to do with high priority bugs - I made an effort to prioritize high-probable bugs, but this information is lost, when priorities are not supported. This could be solved by duplicating bug patterns - e.g. *SQL Injection* for high confidence and *Potential SQL Injection* for medium confidence. The advantage of this would also be that the first rule should have a minimum of false positives and could be used in automatic analysis with alerts. (And the second during manual code reviews.) Another solution is just to add a tag *[high confidence]* to the report (Is the description visible in your tools?). What do you think? (@h3xstream, @ThrawnCA)

**Comment by h3xstream** [comment]
@formanek : The fact that constant string are alerted is a bug/problem. Even in "Audit" mode, I don't want to see those.

The priority filter is applied to all bug patterns. I don't think it's possible to apply to a single bug pattern.

The only remaining bug I see is : https://github.com/h3xstream/find-sec-bugs/blob/b163725fc29a125205e2f56729644394d6b11b67/plugin/src/test/java/com/h3xstream/findsecbugs/injection/stringbuilder/InjectionWithStringBuilderTest.java#L66
This is a huge problem any method should be consider unknown and therefore a tainted source.
It should not be that hard to fix.

**Comment by formanek** [comment]
The fact, that constant strings are alerted (with low confidence) was intended by me, I am just surprised you did not know about that (I think it is quite clear from the code).

I am not sure if you know what I mean about priorities - I want to report a different bug type instead of the same bug type with changed priority only.

Ok, now I see the second problem (I was thinking that this is related to low priorities too). I know about that and I am having it in my to do list. I did not consider this to be so huge problem, because methods modifying its parameter by a tainted source should be quite uncommon. Have you already start to implement this or should I do it?

**Comment by h3xstream** [comment]
@formanek I was aware of the low classification for false positive. The thing I didn't notice was that some real positive would fall in the same priority.. (No blaming here.)

The sudden urgency is related to the Sonar integration. There is no notion of priority in Sonar issue have fix severity (I think).

Yup having multiple bug patterns description could help. I would not rush on it. It require more work to maintain.. there is already specialized description injections.

**Comment by formanek** [comment]
And what about the implementation of making parameter taint unknown for unknown methods? I would do this:
- add support for more mutable parameter indices
- add a method to TaintFrameModelingVisitor, that finds out stack parameter indices excluding those with an object type known to be immutable
- add method for default method summary to TaintMethodSummary
- modify getMethodSummary in TaintFrameModelingVisitor

I think, I can do this tomorrow, if you let me know you are not implementing it yourself.

**Comment by h3xstream** [comment]
@formanek : I have implemented the core idea. (changes to [TaintFrameModelingVisitor.java](https://github.com/h3xstream/find-sec-bugs/commit/8d4ef88a4e0200e22059767d00697905d35e62e8#diff-c1d98326cbc7a19685ad97d009b12372R246))

I see to small change needed to make this solution completed.

### 1. Add support for more mutable parameter indices (as you mention before)
We can either extract it from the signature. Or remember the type in the `Taint` instance.
I assume [SAFE_OBJECT_TYPES](https://github.com/h3xstream/find-sec-bugs/blob/8d4ef88a4e0200e22059767d00697905d35e62e8/plugin/src/main/java/com/h3xstream/findsecbugs/taintanalysis/TaintFrameModelingVisitor.java#L68)

### 2. Add query api to exclusion

Temporary, some methods were added to [methods-summaries.txt](https://github.com/h3xstream/find-sec-bugs/commit/8d4ef88a4e0200e22059767d00697905d35e62e8#diff-c8e698da3e8e027065610aeca5ccbe79R297). This is starting to force the creation of dedicated files for "injectable" api.

```
String sql = "...";
query(sql);
query(sql);
```

The variable `sql` should not be consider as altered after the first query. A couple of api should be strategically chosen to avoid some false positive (logging api, sanitizer, etc.)

**Comment by ThrawnCA** [comment]
@formanek My use case is that I enforce FindBugs checks in our Maven builds, starting with default priority and increasing sensitivity as I fix the bugs. I'm not all that interested in reporting, which people tend not to see up front, or the FindBugs GUI, which is nice when going through and fixing a stack of bugs, but otherwise not a part of our builds. Any time a detector fires, the build fails.

I can (and do) deal with false positives using an exclusion file, but I prefer to do that only if we really are doing something the detector prohibits.

**Comment by h3xstream** [comment]
@formanek If you want to implement the complete fix, you can go ahead. I had trouble implementing the support for the exclusion immutable type.

**Comment by formanek** [comment]
@ThrawnCA Thank you for describing your use case. I think the current settings should be appropriate for you, you just need to stop increasing priority before going to low. Priorities in taint analysis bug patterns are used this way (but *LOW* will be removed probably):
- *HIGH* - high-probable bugs, almost no false positives, useful for build breakers
- *LOW* - ideally **only false positives**, true positives here mean bad analysis
- *MEDIUM* - the rest - analysis could not confirm a tainted sink nor safe input, intended for code review

**Comment by formanek** [comment]
@h3xstream I will try it today or tomorrow. The current implementation is not working for mutable types neither (I see the relevant test switched off).

**Comment by ThrawnCA** [comment]
@formanek I don't think that false positives should have a priority at all. I would expect Low to be used for bugs with limited impact, thus no urgency to fix them. Eg FI_FINALIZER_ONLY_NULLS_FIELDS, or ISC_INSTANTIATE_STATIC_CLASS, are bugs that don't affect much.

**Comment by formanek** [comment]
@ThrawnCA It is actually not a priority (despite using this word in the code), but *confidence* (not related to impact). There is also a *bug rank*, which should be used to order bugs according to how much scary they are.

Everybody wants no false positives to be reported, the problem is that the analysis is quite complex and I cannot guarantee, that no true positives are missed. The approach in ordinary FindBugs detectors is better not to report a potential bug with low probability of being a real bug, because users hate false positives and could stop using FindBugs for this reason. In contrast, FindSecurityBugs is intended for security code review and should not miss any real problem.

I am going to change the detector to report low confidence bugs under a special bug type.

**Comment by h3xstream** [comment]
@formanek What case would fall in the LOW priority?

**Comment by formanek** [comment]
@h3xstream I have already identified (and fixed) bugs in the analysis, that could report true positives with the low confidence. Currently, I'm not aware of any examples of this problem, but since I have not done any large scale testing yet (or not large enough), I'm definitely not 100% confident. We have already agreed on not reporting those, but I'm going to report them under a different bug type (ignored by normal users) to allow review of the analysis, ok?

**Comment by h3xstream** [comment]
Maybe the IGNORE_PRIORITY could be use for that..
..Or a switch could be add (system variable?) to report the FP. This way unless you specify the special argument you don't see the FP.

**Comment by formanek** [comment]
I'm not sure, how various FindBugs plugins handle IGNORE_PRIORITY so I'm afraid the problem could be the same as with LOW_PRIORITY.

I think, I'll make a new bug pattern in the experimental category and report all sinks (for all types of injection) with safe source here. If somebody doesn't like it, I can also do this only if a special parameter is given to FindBugs.

**Comment by ThrawnCA** [comment]
@formanek That sounds fine, thanks.

For me, there would be no need for a parameter. I can just switch off the bug pattern if I don't want it.

**Comment by h3xstream** [comment]
@formanek The problem I see is that we have 8 specialized bug pattern (descriptions). The "potential" false positive would have to be a generic description for all cases.

I am still thinking about option. Maybe we could passed to the short description an indication of the category but it's not good for usability. The short description is not highlight so much in the tools.

**Comment by h3xstream** [comment]
Now that the test case "InjectionWithStringBuilderTest#avoidFalsePositive", it means that the constant string and string derived from safe StringBuilder are not reported. This include the sample provided in the report.

@ThrawnCA  This is the result of the pull request  #78 from @formanek.

I will do a release soon.

**Comment by formanek** [comment]
@h3xstream I fixed some unknown bugs recently and I'm working on making the code more robust, could you wait a few days before doing a release?

**Comment by h3xstream** [comment]
@formanek No problem.
Please create a ticket for the issue/enhancement you are working on.
